# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 05:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_department'),
        ('student', '0002_studentprofile_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='campus.Department'),
            preserve_default=False,
        ),
    ]
